using Avatier.Api.Configuration;
using Avatier.Service.Options;
using Avatier.Service.Services;
using Scalar.AspNetCore;
using Serilog;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSerilog();
builder.Services.AddSerilog((services, configuration) => configuration
                    .ReadFrom.Configuration(builder.Configuration), true);

// Add services to the container.
builder.Services.Configure<LdapOptions>(builder.Configuration.GetSection(LdapOptions.SectionName));
builder.Services.Configure<LogFeederOptions>(builder.Configuration.GetSection("LogFeederOptions"));
builder.Services.AddScoped<ILdapService, LdapService>();

builder.Services.AddControllers(opt =>
{
    opt.Filters.Add<ApiExceptionFilter>();

    opt.Conventions.Add(new ApiResponseConventions());


}).AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Converters.Add(
           new JsonStringEnumConverter());
});

builder.Services.AddOpenApiDocument(config =>
{
    config.Title = "Avatier API";
    config.Version = "v1";
    config.Description = "Avatier API – OpenAPI spec generated by NSwag";
});

if (builder.Environment.IsDevelopment())
{
    builder.Services.AddCors(options =>
    {
        options.AddDefaultPolicy(policy =>
        {
            policy
                .AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod();
        });
    });
}

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{

    app.UseOpenApi();
    app.MapScalarApiReference(options =>
    {
        options
            .WithTitle("Avatier API")
            .WithDefaultHttpClient(ScalarTarget.CSharp, ScalarClient.HttpClient);
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
